### ISSUE TITLE
`npx create-solid-app` broken for some templates

### ISSUE THREAD

**Issue by davedbase** [Harry-Hopkinson/create-solid-app#1079]
@Harry-Hopkinson I've received 2-3 comments and concerns in the Solid Community Discord regarding create-solid-app. It seems that the bot setup is maintaining the `solid-js` dependency however the published version is very far behind. For example if you attempt installing the ts-tailwind package it uses 1.6 and vite-plugin-soid is a few major versions behind as well.

Here's the package.json once installed:

```json
{
  "name": "solidweb",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "license": "MIT",
  "devDependencies": {
    "autoprefixer": "10.4.14",
    "postcss": "8.4.21",
    "tailwindcss": "3.2.7",
    "typescript": "5.0.2",
    "vite": "4.2.1",
    "vite-plugin-solid": "2.6.1"
  },
  "dependencies": {
    "solid-js": "1.6.15"
  }
}
```
I was wondering if you might have a chance to update the packages for us?

Thank you kindly.

**Comment by Harry-Hopkinson** [comment]
Done 😃 - I have released the new version with the updated packages.

**Comment by Harry-Hopkinson** [comment]
I will make sure that I maintain this package more often.

**Comment by davedbase** [comment]
Thank you so much for such a quick response. The community appreciates you! 🙌
